version: 0.2
env:
  variables:
    NODE_ENV: test        # Užtikrina, kad serveris nepasileis testuojant

phases:
  install:
    commands:
      - echo "Įdiegiamos priklausomybės..."
      - npm ci
  build:
    commands:
      - echo "Vykdomi jest testai..."
      - npx jest --ci
