version: 0.2

phases:
  install:
    commands:
      - echo "[INSTALL] Installing dependencies..."
      - npm install
      - echo "[INSTALL] Installing Semgrep..."
      - pip install semgrep
  build:
    commands:
      - echo "[SAST] Detecting hardcoded secrets with specific Semgrep rule"
      - semgrep --config="https://semgrep.dev/r/javascript.lang.security.detect-hardcoded-secret" .
