version: 0.2

phases:
  install:
    commands:
      - echo "[INSTALL] Installing dependencies..."
      - npm install
      - echo "[INSTALL] Installing Semgrep..."
      - pip install semgrep
  build:
    commands:
      - echo "[SAST] Running Semgrep checks..."
      - semgrep --config=p/secrets .
      - semgrep --config=p/nodejs .
      - semgrep --config=p/security-audit .
      - semgrep --config=r/javascript.lang.security.detect-hardcoded-secret .
      - semgrep --config=r/javascript.lang.security.detect-eval .
      - semgrep --config=r/javascript.lang.security.detect-new-buffer .
      - semgrep --config=r/javascript.lang.security.detect-dangerous-regex .

