version: 0.2

env:
  variables:
    TARGET_URL: "http://DevOpsGettingStarted-env.eba-pymurxcf.eu-north-1.elasticbeanstalk.com"

phases:
  install:
    runtime-versions:
      docker: 20
    commands:
      - echo "[INSTALL] Docker ready."

  build:
    commands:
      - echo "[ZAP] Running OWASP ZAP baseline scan..."
      - docker pull owasp/zap2docker-stable
      - docker run --rm owasp/zap2docker-stable zap-baseline.py -t "$TARGET_URL" -r zap-report.html

  post_build:
    commands:
      - echo "[ZAP] DAST scan complete. Report saved to zap-report.html"

artifacts:
  files:
    - zap-report.html

