version: 0.2

phases:
  install:
    commands:
      - echo "[INSTALL] Installing dependencies..."
      - npm install
      - echo "[INSTALL] Installing Semgrep..."
      - pip install semgrep
  build:
    commands:
      - echo "[SAST] Running Semgrep with multiple configurations"
      - semgrep scan --config=r/javascript.lang.security.detect-hardcoded-secret,auto .

