version: 0.2

env:
  variables:
    NODE_ENV: test  # Užtikrina, kad serveris nepasileistų testuojant

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Įdiegiamos priklausomybės..."
      - npm ci

  build:
    commands:
      - echo "Vykdomi jest testai, IR matuojama Jest trukmė..."
      - time npx jest --ci --runInBand
