version: 0.2

phases:
  install:
    commands:
      - echo "Įjungiamas Docker palaikymas OWASP ZAP skanavimui..."
  pre_build:
    commands:
      - echo "Paleidžiamas Node.js serveris testavimui..."
      - nohup node app.js &
      - sleep 10
  build:
    commands:
      - echo "Paleidžiamas OWASP ZAP skanavimas..."
      - docker run --network=host -v $(pwd):/zap/wrk ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost:8080 -g gen.conf -r zap_report.html
artifacts:
  files:
    - zap_report.html
