version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      python: 3.11
    commands:
      - echo [INSTALL] Installing Node.js dependencies...
      - npm ci
      - echo [INSTALL] Installing Semgrep...
      - pip install --upgrade pip
      - pip install semgrep

  build:
    commands:
      - echo [BUILD] Running npm audit with high severity check...
      - npm audit --audit-level=high
      - echo [BUILD] Running Semgrep with enhanced ruleset...
      - semgrep scan \
          --config=p/security-audit .

artifacts:
  files:
    - '**/*'
