version: 0.2

phases:
  install:
    commands:
      - echo "Įjungiamas Docker palaikymas OWASP ZAP skanavimui..."
  pre_build:
    commands:
      - echo "Instaliuojamos Node.js priklausomybės..."
      - npm install
      - echo "Paleidžiamas Node.js serveris testavimui..."
      - nohup node app.js > app.log 2>&1 &
      - sleep 10
  build:
    commands:
      - echo "Paleidžiamas OWASP ZAP skanavimas, IR matuoja OWASP ZAP trukmę..."
      - time docker run --user root --network=host -v $(pwd):/zap/wrk:rw ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost:8080 -g gen.conf -r zap_report.html -J zap_report.json -d || true
      - echo "Užmušamas Node.js serveris po testavimo..."
      - pkill -f "node app.js" || true

