phases:
  install:
    commands:
      - echo "[INSTALL] Installing dependencies..."
      - npm install
  build:
    commands:
      - echo "[SAST] Running Semgrep with detect-hardcoded-secret"
      - semgrep scan --config=r/javascript.lang.security.detect-hardcoded-secret .

