version: 0.2

phases:
  install:
    commands:
      - echo "[INSTALL] Installing dependencies..."
      - npm install
      - echo "[INSTALL] Installing Semgrep..."
      - pip install semgrep
  build:
    commands:
      - echo "[SAST] Running Semgrep to detect hardcoded secrets"
      - semgrep --config=p/javascript --include-rule=javascript.lang.security.detect-hardcoded-secret .

