version: 0.2

phases:
  install:
    commands:
      - echo "[INSTALL] Installing dependencies..."
      - npm ci
  build:
    commands:
      - echo "[TEST] Running Jest tests..."
      - npm test

artifacts:
  files:
    - '**/*'

