version: 0.2

env:
  variables:
    TARGET_URL: "http://DevOpsGettingStarted-env.eba-pymurxcf.eu-north-1.elasticbeanstalk.com"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "[INSTALL] Installing dependencies..."
      - yum update -y && yum install -y wget unzip
      - wget https://github.com/zaproxy/zaproxy/releases/download/v2.14.0/ZAP_2.14.0_unix.tar.gz
      - mkdir -p $HOME/zap
      - tar -xzf ZAP_2.14.0_unix.tar.gz -C $HOME/zap --strip-components=1
  build:
    commands:
      - echo "[ZAP] Running OWASP ZAP baseline scan..."
      - $HOME/zap/zap.sh -cmd -quickurl "$TARGET_URL" -quickout zap-report.html
  post_build:
    commands:
      - echo "[ZAP] DAST scan complete. Report saved to zap-report.html"

artifacts:
  files:
    - zap-report.html

